### ISSUE TITLE
need updated description arg in setup.py

### ISSUE THREAD

**Issue by reduxionist** [lambdalisue/django-roughpages#5]
This caught my eye on PyPI; currently the leftover description from django-permission is still present in setup.py:

```
    description=('A enhanced permission system which enable logical permission'
                 'systems to complex permissions')
```

I'd have opened a PR rather than an issue if descriptions weren't such a personal decision...

Thanks for sharing your code! 😄

**Comment by lambdalisue** [comment]
Oops. Thanks. I haven't noticed that.

**Comment by lambdalisue** [comment]
Fixed.https://pypi.python.org/pypi/django-roughpages/
